-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Računalo: localhost
-- Vrijeme generiranja: Lip 15, 2019 u 02:12 AM
-- Verzija poslužitelja: 5.1.41
-- PHP verzija: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Baza podataka: `bbcnews`
--

-- --------------------------------------------------------

--
-- Tablična struktura za tablicu `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ime` varchar(32) COLLATE cp1250_croatian_ci NOT NULL,
  `prezime` varchar(32) COLLATE cp1250_croatian_ci NOT NULL,
  `username` varchar(32) COLLATE cp1250_croatian_ci NOT NULL,
  `password` varchar(255) COLLATE cp1250_croatian_ci NOT NULL,
  `razina` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=MyISAM  DEFAULT CHARSET=cp1250 COLLATE=cp1250_croatian_ci AUTO_INCREMENT=8 ;

--
-- Izbacivanje podataka za tablicu `users`
--

INSERT INTO `users` (`id`, `ime`, `prezime`, `username`, `password`, `razina`) VALUES
(2, 'dundo', 'maroje', 'dmaroje', '$2y$10$UrPrmXlxhYexUhu/EEpeC.4GBynphbN1VPyGOp0qYNiJAxVS6Eela', 1),
(3, 'root', 'root', 'root', '$2y$10$516Ay2sE475LMHUNUGO3rO62hDihzXxzo2V9Og7CgoRJLxWiL/l56', 1),
(4, 'ivo', 'horvat', 'pero', '$2y$10$azXo8iR/quqlbzz1Qoq8l.sdcr/FF.l708Pl/wRQkop8cGzOmNJQe', 0),
(5, 'stef', 'sef', 'sef', '$2y$10$FA0DIXCTaC/uv4SLc..XjOp9MSsT0/GhYnBu5rMvgAPhDxUiVJkXq', 0),
(6, 'dasdas', 'adsdas', 'asdasdasd', '$2y$10$oHT0Vje4Uyb5AuNsLY874eZ21RYs1KkWgcSFLGRiXVYu8/gHRXCXC', 0),
(7, 'admin', 'admin', 'admin', '$2y$10$DRJec74gYNJu3viUgXKkHuOgtVIKB4RXJEzRplmWbndI7YfA2QBEe', 1);

-- --------------------------------------------------------

--
-- Tablična struktura za tablicu `vijesti`
--

CREATE TABLE IF NOT EXISTS `vijesti` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `datum` date NOT NULL,
  `naslov` varchar(128) COLLATE cp1250_croatian_ci NOT NULL,
  `sazetak` varchar(1024) COLLATE cp1250_croatian_ci NOT NULL,
  `clanak` text COLLATE cp1250_croatian_ci NOT NULL,
  `slika` varchar(32) COLLATE cp1250_croatian_ci NOT NULL,
  `kategorija` varchar(32) COLLATE cp1250_croatian_ci NOT NULL,
  `arhiva` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_3` (`id`),
  KEY `id` (`id`),
  KEY `id_2` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=cp1250 COLLATE=cp1250_croatian_ci AUTO_INCREMENT=42 ;

--
-- Izbacivanje podataka za tablicu `vijesti`
--

INSERT INTO `vijesti` (`id`, `datum`, `naslov`, `sazetak`, `clanak`, `slika`, `kategorija`, `arhiva`) VALUES
(26, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/19IEJZnVSb.jpg', 'NEWS', 0),
(25, '2019-05-24', 'Lorem ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/QiY0OCV9ul.jpg', 'NEWS', 0),
(24, '2019-05-24', 'Lorem ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quom porttitor nec. Maecenas lo mai, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Done varius sed orci a egestas.', 'imgs/RsOndl94A1.jpg', 'SPORT', 0),
(27, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/i0hdD7FLEq.jpg', 'NEWS', 0),
(28, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/xbRU1wyBVt.jpg', 'SPORT', 0),
(29, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/vyCE9UqGoJ.jpg', 'SPORT', 0),
(30, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/jYSuTiK6DI.jpg', 'SPORT', 0),
(31, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/2ti1ndWCIX.jpg', 'SPORT', 0),
(32, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/1QiloDxv6C.jpg', 'SPORT', 0),
(33, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/8kuTqNW2mv.jpg', 'NEWS', 0),
(34, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/EU1hM0obK3.jpg', 'NEWS', 0),
(35, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/feqSYlmAxg.jpg', 'SPORT', 0),
(36, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/6LJWg4RFbX.jpg', 'SPORT', 0),
(37, '2019-05-24', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet quam quis dui euismod facilisis. Ut quis turpis maximus sapien iaculis rutrum at quis velit. Sed lacinia libero ante, et vulputate quam porttitor nec. Maecenas leo mi, consequat ut venenatis vel, maximus a massa. In volutpat eget dui vel vestibulum. Phasellus ultricies, justo malesuada dictum ornare, mauris dolor sollicitudin felis, id lobortis lorem nunc in tortor. Suspendisse ornare facilisis dolor, eu rutrum orci dapibus quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula eros nibh, quis convallis risus faucibus eu. Donec varius sed orci a egestas.', 'imgs/zVlSxvMt9F.jpg', 'NEWS', 0),
(39, '2019-06-14', 'Lorem ipsu', 'Pellentesque rutrum purus in risus fermentum gravida. Nulla tristique, ipsum sed pharetra placerat, nunc lacus ultrices turpis, eu posuere enim tellus vitae leo. Quisque pretium justo et porta gravida.', 'Pellentesque rutrum purus in risus fermentum gravida. Nulla tristique, ipsum sed pharetra placerat, nunc lacus ultrices turpis, eu posuere enim tellus vitae leo. Quisque pretium justo et porta gravida. Nunc quis porta nulla. Vestibulum dignissim leo nec euismod faucibus. Vestibulum elit magna, dapibus id ante sed, pharetra tempus justo. Nulla ut dui sit amet lectus maximus vehicula nec ac risus. Praesent tincidunt, augue nec rutrum tincidunt, lorem odio iaculis tellus, et fermentum metus justo non nulla. Phasellus fringilla euismod lectus. Nulla feugiat, nunc vel iaculis lacinia, justo lacus consequat erat, in cursus elit leo nec risus. Quisque non diam vestibulum, dictum mauris id, commodo arcu. Nam aliquam lectus a bibendum bibendum.', 'imgs/WRP1eCJHQh.jpg', 'sport', 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
